//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitMobile.StoreDataService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class addAnOrderWithoutApprovedResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
                this.RaisePropertyChanged("returnSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class addAnOrderWithoutApproved : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private int arg2Field;
        
        private bool arg2FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
                this.RaisePropertyChanged("arg2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg2Specified {
            get {
                return this.arg2FieldSpecified;
            }
            set {
                this.arg2FieldSpecified = value;
                this.RaisePropertyChanged("arg2Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class addAnOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        private bool returnFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnSpecified {
            get {
                return this.returnFieldSpecified;
            }
            set {
                this.returnFieldSpecified = value;
                this.RaisePropertyChanged("returnSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class addAnOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int arg0Field;
        
        private bool arg0FieldSpecified;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private int arg3Field;
        
        private bool arg3FieldSpecified;
        
        private int arg4Field;
        
        private bool arg4FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg0Specified {
            get {
                return this.arg0FieldSpecified;
            }
            set {
                this.arg0FieldSpecified = value;
                this.RaisePropertyChanged("arg0Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
                this.RaisePropertyChanged("arg2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
                this.RaisePropertyChanged("arg3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg3Specified {
            get {
                return this.arg3FieldSpecified;
            }
            set {
                this.arg3FieldSpecified = value;
                this.RaisePropertyChanged("arg3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int arg4 {
            get {
                return this.arg4Field;
            }
            set {
                this.arg4Field = value;
                this.RaisePropertyChanged("arg4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arg4Specified {
            get {
                return this.arg4FieldSpecified;
            }
            set {
                this.arg4FieldSpecified = value;
                this.RaisePropertyChanged("arg4Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class getAnOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private order returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public order @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string firstNameField;
        
        private int ifApprovedField;
        
        private bool ifApprovedFieldSpecified;
        
        private string lastNameField;
        
        private int orderIDField;
        
        private bool orderIDFieldSpecified;
        
        private int planIDField;
        
        private bool planIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ifApproved {
            get {
                return this.ifApprovedField;
            }
            set {
                this.ifApprovedField = value;
                this.RaisePropertyChanged("ifApproved");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ifApprovedSpecified {
            get {
                return this.ifApprovedFieldSpecified;
            }
            set {
                this.ifApprovedFieldSpecified = value;
                this.RaisePropertyChanged("ifApprovedSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int orderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
                this.RaisePropertyChanged("orderID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderIDSpecified {
            get {
                return this.orderIDFieldSpecified;
            }
            set {
                this.orderIDFieldSpecified = value;
                this.RaisePropertyChanged("orderIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int planID {
            get {
                return this.planIDField;
            }
            set {
                this.planIDField = value;
                this.RaisePropertyChanged("planID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool planIDSpecified {
            get {
                return this.planIDFieldSpecified;
            }
            set {
                this.planIDFieldSpecified = value;
                this.RaisePropertyChanged("planIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class getAnOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BitMobile/")]
    public partial class getOrdersList : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://BitMobile/", ConfigurationName="StoreDataService.StoreDataQuery")]
    public interface StoreDataQuery {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/addAnOrderWithoutApprovedRequest", ReplyAction="http://BitMobile/StoreDataQuery/addAnOrderWithoutApprovedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApprovedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApproved))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getOrdersList))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BitMobile.StoreDataService.addAnOrderWithoutApprovedResponse1 addAnOrderWithoutApproved(BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/addAnOrderWithoutApprovedRequest", ReplyAction="http://BitMobile/StoreDataQuery/addAnOrderWithoutApprovedResponse")]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.addAnOrderWithoutApprovedResponse1> addAnOrderWithoutApprovedAsync(BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/getAnOrderRequest", ReplyAction="http://BitMobile/StoreDataQuery/getAnOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApprovedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApproved))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getOrdersList))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BitMobile.StoreDataService.getAnOrderResponse1 getAnOrder(BitMobile.StoreDataService.getAnOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/getAnOrderRequest", ReplyAction="http://BitMobile/StoreDataQuery/getAnOrderResponse")]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.getAnOrderResponse1> getAnOrderAsync(BitMobile.StoreDataService.getAnOrderRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/addAnOrderRequest", ReplyAction="http://BitMobile/StoreDataQuery/addAnOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApprovedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApproved))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getOrdersList))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BitMobile.StoreDataService.addAnOrderResponse1 addAnOrder(BitMobile.StoreDataService.addAnOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/addAnOrderRequest", ReplyAction="http://BitMobile/StoreDataQuery/addAnOrderResponse")]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.addAnOrderResponse1> addAnOrderAsync(BitMobile.StoreDataService.addAnOrderRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/getOrdersListRequest", ReplyAction="http://BitMobile/StoreDataQuery/getOrdersListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BitMobile.StoreDataService.SQLException), Action="http://BitMobile/StoreDataQuery/getOrdersList/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApprovedResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderWithoutApproved))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAnOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getOrdersList))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BitMobile.StoreDataService.getOrdersListResponse getOrdersList(BitMobile.StoreDataService.getOrdersListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://BitMobile/StoreDataQuery/getOrdersListRequest", ReplyAction="http://BitMobile/StoreDataQuery/getOrdersListResponse")]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.getOrdersListResponse> getOrdersListAsync(BitMobile.StoreDataService.getOrdersListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAnOrderWithoutApproved", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class addAnOrderWithoutApprovedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public addAnOrderWithoutApprovedRequest() {
        }
        
        public addAnOrderWithoutApprovedRequest(string arg0, string arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAnOrderWithoutApprovedResponse", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class addAnOrderWithoutApprovedResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public addAnOrderWithoutApprovedResponse1() {
        }
        
        public addAnOrderWithoutApprovedResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAnOrder", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class getAnOrderRequest {
        
        public getAnOrderRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAnOrderResponse", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class getAnOrderResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BitMobile.StoreDataService.order @return;
        
        public getAnOrderResponse1() {
        }
        
        public getAnOrderResponse1(BitMobile.StoreDataService.order @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAnOrder", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class addAnOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        public addAnOrderRequest() {
        }
        
        public addAnOrderRequest(int arg0, string arg1, string arg2, int arg3, int arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAnOrderResponse", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class addAnOrderResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public addAnOrderResponse1() {
        }
        
        public addAnOrderResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersList", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class getOrdersListRequest {
        
        public getOrdersListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersListResponse", WrapperNamespace="http://BitMobile/", IsWrapped=true)]
    public partial class getOrdersListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://BitMobile/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] @return;
        
        public getOrdersListResponse() {
        }
        
        public getOrdersListResponse(object[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StoreDataQueryChannel : BitMobile.StoreDataService.StoreDataQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreDataQueryClient : System.ServiceModel.ClientBase<BitMobile.StoreDataService.StoreDataQuery>, BitMobile.StoreDataService.StoreDataQuery {
        
        public StoreDataQueryClient() {
        }
        
        public StoreDataQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreDataQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreDataQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreDataQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BitMobile.StoreDataService.addAnOrderWithoutApprovedResponse1 BitMobile.StoreDataService.StoreDataQuery.addAnOrderWithoutApproved(BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest request) {
            return base.Channel.addAnOrderWithoutApproved(request);
        }
        
        public int addAnOrderWithoutApproved(string arg0, string arg1, int arg2) {
            BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest inValue = new BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            BitMobile.StoreDataService.addAnOrderWithoutApprovedResponse1 retVal = ((BitMobile.StoreDataService.StoreDataQuery)(this)).addAnOrderWithoutApproved(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.addAnOrderWithoutApprovedResponse1> BitMobile.StoreDataService.StoreDataQuery.addAnOrderWithoutApprovedAsync(BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest request) {
            return base.Channel.addAnOrderWithoutApprovedAsync(request);
        }
        
        public System.Threading.Tasks.Task<BitMobile.StoreDataService.addAnOrderWithoutApprovedResponse1> addAnOrderWithoutApprovedAsync(string arg0, string arg1, int arg2) {
            BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest inValue = new BitMobile.StoreDataService.addAnOrderWithoutApprovedRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((BitMobile.StoreDataService.StoreDataQuery)(this)).addAnOrderWithoutApprovedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BitMobile.StoreDataService.getAnOrderResponse1 BitMobile.StoreDataService.StoreDataQuery.getAnOrder(BitMobile.StoreDataService.getAnOrderRequest request) {
            return base.Channel.getAnOrder(request);
        }
        
        public BitMobile.StoreDataService.order getAnOrder() {
            BitMobile.StoreDataService.getAnOrderRequest inValue = new BitMobile.StoreDataService.getAnOrderRequest();
            BitMobile.StoreDataService.getAnOrderResponse1 retVal = ((BitMobile.StoreDataService.StoreDataQuery)(this)).getAnOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.getAnOrderResponse1> BitMobile.StoreDataService.StoreDataQuery.getAnOrderAsync(BitMobile.StoreDataService.getAnOrderRequest request) {
            return base.Channel.getAnOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<BitMobile.StoreDataService.getAnOrderResponse1> getAnOrderAsync() {
            BitMobile.StoreDataService.getAnOrderRequest inValue = new BitMobile.StoreDataService.getAnOrderRequest();
            return ((BitMobile.StoreDataService.StoreDataQuery)(this)).getAnOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BitMobile.StoreDataService.addAnOrderResponse1 BitMobile.StoreDataService.StoreDataQuery.addAnOrder(BitMobile.StoreDataService.addAnOrderRequest request) {
            return base.Channel.addAnOrder(request);
        }
        
        public int addAnOrder(int arg0, string arg1, string arg2, int arg3, int arg4) {
            BitMobile.StoreDataService.addAnOrderRequest inValue = new BitMobile.StoreDataService.addAnOrderRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            BitMobile.StoreDataService.addAnOrderResponse1 retVal = ((BitMobile.StoreDataService.StoreDataQuery)(this)).addAnOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.addAnOrderResponse1> BitMobile.StoreDataService.StoreDataQuery.addAnOrderAsync(BitMobile.StoreDataService.addAnOrderRequest request) {
            return base.Channel.addAnOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<BitMobile.StoreDataService.addAnOrderResponse1> addAnOrderAsync(int arg0, string arg1, string arg2, int arg3, int arg4) {
            BitMobile.StoreDataService.addAnOrderRequest inValue = new BitMobile.StoreDataService.addAnOrderRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((BitMobile.StoreDataService.StoreDataQuery)(this)).addAnOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BitMobile.StoreDataService.getOrdersListResponse BitMobile.StoreDataService.StoreDataQuery.getOrdersList(BitMobile.StoreDataService.getOrdersListRequest request) {
            return base.Channel.getOrdersList(request);
        }
        
        public object[] getOrdersList() {
            BitMobile.StoreDataService.getOrdersListRequest inValue = new BitMobile.StoreDataService.getOrdersListRequest();
            BitMobile.StoreDataService.getOrdersListResponse retVal = ((BitMobile.StoreDataService.StoreDataQuery)(this)).getOrdersList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BitMobile.StoreDataService.getOrdersListResponse> BitMobile.StoreDataService.StoreDataQuery.getOrdersListAsync(BitMobile.StoreDataService.getOrdersListRequest request) {
            return base.Channel.getOrdersListAsync(request);
        }
        
        public System.Threading.Tasks.Task<BitMobile.StoreDataService.getOrdersListResponse> getOrdersListAsync() {
            BitMobile.StoreDataService.getOrdersListRequest inValue = new BitMobile.StoreDataService.getOrdersListRequest();
            return ((BitMobile.StoreDataService.StoreDataQuery)(this)).getOrdersListAsync(inValue);
        }
    }
}
